####################
#### SOFTWARE
elai: "/shared/projects/vietcaf/scripts/elai/elai-lin" # "/data3/projects/vietcaf/baotram/scripts/robusta_vn/elai/elai-lin"
vcftools: "vcftools/0.1.16"
singularity: "/shared/projects/vietcaf/scripts/snakelai/singularity-container_myr_4-0-2_rstudio_1.3.sif"

####################
#### INPUT FILES

genome: "/shared/projects/vietcaf/data/reference/CC1.8_v2_pseudomolecule_cat.fa" # reference, only used if run "Snakemake merge_elai"

source_files: []
test_file: "" # if filled, test_id will be ignored
snp_file: ""

source_vcf: "/shared/projects/most_kmer/vcf_bgi_2021/gbp_output/filtered_vcf_by_chrom/african_final.recode.vcf"
test_vcf: "/shared/projects/most_kmer/vcf_bgi_2021/gbp_output/filtered_vcf_by_chrom/vn_final.recode.vcf"
test_id: "@" # "@" for all genotypes, otherwise, specify id names to test
chromosome: "@" # "@" for all chromosome, otherwise, specify chroms to test

####################
#### OUTPUT
outdir: "/shared/projects/elai_most/data/snakelai_out_all"

######################
#### SNP SELECTION
split_snps_cores: 20
snp_selection:
  even: # 1 snp per non-overlapping windows of 5000 bpp
    nb_snps: 1 
    window_size: 5000 
  all: # all snps splitted into chunks of 100000 snps
    nb_snps: "all" 
    window_size: 100000 


######################
#### SOURCE GENOTYPES SIMULATION
simulate_source: TRUE
nb_groups: 5
nb_genotypes: 100 # nb of genotypes per group
simulate_cores: 5
simulate_mem_gb: 20

####################
#### ELAI PARAMS

elai_params:
  c5_mg20: "-c 5 -mixgen 20 --exclude-nopos --exclude-miss1"
  #c5_mg10_s60: "-c 5 -mixgen 10 -s 60 --exclude-nopos --exclude-miss1"

elai_mem_gb: 20

#######################
#### MERGE ELAI RESULTS
# only works if run "Snakemake merge_elai"
merged_snps: ["even", "all"]
merged_params: "c5_mg_20"

